import type {NodeAdapterOfConfigurationOfEnvironmentOfSource} from "../implementations/node/NodeAdapterOfConfigurationOfEnvironmentOfSource.ts";
export type SupportedAdapterOfConfigurationOfEnvironmentOfSource =
	NodeAdapterOfConfigurationOfEnvironmentOfSource | null;
