import type {NodeAdapterOfConfigurationOfEnvironmentOfBuilding} from "../implementations/Node/NodeAdapterOfConfigurationOfEnvironmentOfBuilding.ts";
export type SupportedAdapterOfConfigurationOfEnvironmentOfBuilding =
	NodeAdapterOfConfigurationOfEnvironmentOfBuilding | null;
